def build(bld):
    sources = ['lexer_tests.c',
               'test_single_token.c',
               'test_multiple_tokens.c']
    bld(features = 'c',
        source = sources,
        includes = [bld.env.INCLUDE_GENERATED_SRC, bld.env.INCLUDE_CUTEST, 
                    bld.env.INCLUDE_SRC, bld.env.INCLUDE_SPECTACULAR],
        name = 'lexer_tests')
