def build(bld):
    sources = ['test_identifier.c',
               'test_ast_walk.c']
    bld(features = 'c',
        source = sources,
        includes = [bld.env.INCLUDE_SRC, bld.env.INCLUDE_CUTEST],
        name = 'ast_tests',
        use = ['ast', 'cutest'])

