def build(bld):
    sources = ['test_identifier.c',
               'test_binary_operation.c',
               'test_integer.c',
               'test_boolean.c',
               'test_new_object.c',
               'test_this.c',
               'test_ast_list.c',
               'test_call.c',
               'test_unary_operation.c',
               'test_ast_walk.c']
    bld(features = 'c',
        source = sources,
        includes = [bld.env.INCLUDE_SRC, bld.env.INCLUDE_CUTEST],
        name = 'ast_tests')
