def build(bld):
    sources = bld.path.ant_glob('*.c')
    bld(features = 'c',
        source = sources,
        includes = [bld.env.INCLUDE_GENERATED_SRC, bld.env.INCLUDE_SPECS,
                    bld.env.INCLUDE_SPECTACULAR, bld.env.INCLUDE_SRC],
        name = 'lexer_specs')
