def build(bld):
    sources = ['single_token_spec.c',
               'multiple_tokens_spec.c']
    bld(features = 'c',
        source = sources,
        includes = [bld.env.INCLUDE_GENERATED_SRC, bld.env.INCLUDE_CUTEST, 
                    bld.env.INCLUDE_SRC, bld.env.INCLUDE_SPECTACULAR],
        name = 'lexer_specs')
