def build(bld):
    bld.recurse(['lexer', 'parser', 'ast', 'list', 'errors'])
    sources = ['all_specs.c']
    bld(features = 'c cprogram',
        source = sources,
        target = 'run_all_specs',
        includes = [bld.env.INCLUDE_SPECTACULAR],
        use = ['lexer_specs', 'parser_specs', 'ast_specs', 'list_specs',
               'errors_specs', 'parser', 'lexer', 'spectacular', 'objects'])
