def build(bld):
    bld.recurse(['lexer', 'parser', 'ast'])
    sources = bld.path.ant_glob('*.c')
    bld(features = 'c cprogram',
        source = sources,
        target = 'run_all_specs',
        includes = [bld.env.INCLUDE_SPECTACULAR, bld.env.INCLUDE_SRC],
        use = ['lexer_specs', 'parser_specs', 'ast_specs', 'parser', 'lexer', 
               'spectacular', 'objects'])
