def build(bld):
    bld(features = 'c bison', source = 'jurov.y', 
        includes = '.', name = 'parser')
    bld(features = 'c flex', source = 'jurov.l', includes = '.', 
        name = 'lexer', cflags = bld.env.CFLAGS + ['-D _POSIX_SOURCE'])
    sources = bld.path.ant_glob('*.c') 
    bld(features = 'c', source = sources, includes = '.', 
        name = 'objects')
