def build(bld):
    sources = ['main_class_spec.c',
               'statements_spec.c']
    bld(features = 'c',
        source = sources,
        includes = [bld.env.INCLUDE_GENERATED_SRC, bld.env.INCLUDE_SPECTACULAR, 
                    bld.env.INCLUDE_SRC, bld.env.INCLUDE_SPECS],
        name = 'parser_specs')
